#!/bin/bash
# Enhanced Job Summary Generator
# This script creates a user-friendly summary in GitHub Actions

cd /home/runner/work/sample-flask-app/sample-flask-app/pipeline

# Create comprehensive summary
echo "## 🤖 AI TestGen Pipeline Results" >> $GITHUB_STEP_SUMMARY
echo "" >> $GITHUB_STEP_SUMMARY

# Check if summary.json exists
if [ -f summary.json ]; then
  # Extract metrics
  COVERAGE=$(jq -r '.coverage.line_coverage // "N/A"' summary.json)
  TESTS_PASSED=$(jq -r '.tests.results.passed // 0' summary.json)
  TESTS_FAILED=$(jq -r '.tests.results.failed // 0' summary.json)
  TESTS_GENERATED=$(jq -r '.tests.generated.count // 0' summary.json)
  TOTAL_TESTS=$(jq -r '.tests.results.total // 0' summary.json)
  
  # Status
  if [ "$TESTS_FAILED" -eq 0 ]; then
    STATUS="✅ All Tests Passed"
  else
    STATUS="❌ Some Tests Failed"
  fi
  
  # Coverage badge
  if (( $(echo "$COVERAGE >= 90" | bc -l) )); then
    COV_BADGE="🟢 Excellent"
  elif (( $(echo "$COVERAGE >= 70" | bc -l) )); then
    COV_BADGE="🟡 Good"
  else
    COV_BADGE="🔴 Needs Improvement"
  fi
  
  echo "### $STATUS" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
  
  # Metrics Table
  echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
  echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
  echo "| 📊 **Coverage** | **${COVERAGE}%** $COV_BADGE |" >> $GITHUB_STEP_SUMMARY
  echo "| ✅ **Tests Passed** | $TESTS_PASSED |" >> $GITHUB_STEP_SUMMARY
  echo "| ❌ **Tests Failed** | $TESTS_FAILED |" >> $GITHUB_STEP_SUMMARY
  echo "| 📝 **Total Tests** | $TOTAL_TESTS |" >> $GITHUB_STEP_SUMMARY
  echo "| 🤖 **AI Generated** | $TESTS_GENERATED |" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
  
  # Coverage Bar
  echo "### 📈 Coverage Progress" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
  COVERAGE_INT=${COVERAGE%.*}
  FILLED=$((COVERAGE_INT / 5))
  EMPTY=$((20 - FILLED))
  BAR=$(printf '█%.0s' $(seq 1 $FILLED))$(printf '░%.0s' $(seq 1 $EMPTY))
  echo "\`$BAR\` ${COVERAGE}%" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
  
  # Artifacts
  echo "### 📦 Download Reports" >> $GITHUB_STEP_SUMMARY
  echo "" >> $GITHUB_STEP_SUMMARY
  echo "- 📊 Coverage Reports (HTML + XML)" >> $GITHUB_STEP_SUMMARY
  echo "- 🧪 Test Results (JUnit XML)" >> $GITHUB_STEP_SUMMARY
  echo "- 📄 Summary JSON" >> $GITHUB_STEP_SUMMARY
  
else
  echo "⚠️ Summary not available" >> $GITHUB_STEP_SUMMARY
fi

echo "" >> $GITHUB_STEP_SUMMARY
echo "---" >> $GITHUB_STEP_SUMMARY
echo "*Generated by AI TestGen*" >> $GITHUB_STEP_SUMMARY
